Add OSX support

diff --git a/start b/start
--- a/start
+++ b/start
@@ -6,6 +6,11 @@ command -v unzip >/dev/null || { echo "unzip is not installed. Aborting." >&2; e
 
 SCRIPT_HOME=$PWD
 
+OS_SUFFIX="linux"
+if [[ "$OSTYPE" == "darwin"* ]]; then
+    let OS_SUFFIX="macosx"
+fi
+
 setSDKPath () {
     echo -n "Please provide Android SDK location (ex: /mnt/tools/android-sdk):"
     read answer
@@ -23,22 +28,23 @@ getAndroidSDK() {
     echo "Downloading Android SDK tools..."
     mkdir android-sdk
     cd android-sdk
-    curl -O https://dl.google.com/android/repository/tools_r25.2.5-linux.zip
-    [ -f "tools_r25.2.5-linux.zip" ] || { echo "Download failed. Aborting." ; exit 1 ;}
+
+    curl -O https://dl.google.com/android/repository/tools_r25.2.5-$OS_SUFFIX.zip
+    [ -f "tools_r25.2.5-$OS_SUFFIX.zip" ] || { echo "Download failed. Aborting." ; exit 1 ;}
     echo
     echo -n "Configuring Android SDK tools..."
-    unzip -q tools_r25.2.5-linux.zip
-    rm tools_r25.2.5-linux.zip
+    unzip -q tools_r25.2.5-$OS_SUFFIX.zip
+    rm tools_r25.2.5-$OS_SUFFIX.zip
     echo "   Done!"
 
     echo
     echo "Downloading Android platform tools..."
-    curl -O http://dl.google.com/android/repository/platform-tools_r25.0.3-linux.zip
-    [ -f "platform-tools_r25.0.3-linux.zip" ] || { echo "Download failed. Aborting." ; exit 1 ;}
+    curl -O http://dl.google.com/android/repository/platform-tools_r25.0.3-$OS_SUFFIX.zip
+    [ -f "platform-tools_r25.0.3-$OS_SUFFIX.zip" ] || { echo "Download failed. Aborting." ; exit 1 ;}
     echo
     echo -n "Configuring Android platform tools..."
-    unzip -q platform-tools_r25.0.3-linux.zip
-    rm platform-tools_r25.0.3-linux.zip
+    unzip -q platform-tools_r25.0.3-$OS_SUFFIX.zip
+    rm platform-tools_r25.0.3-$OS_SUFFIX.zip
     cd ..
     echo "$PWD/android-sdk" > sdklocation
     echo "   Done!"
@@ -128,6 +134,7 @@ startAVD() {
 echo "+----------------------------------------------------------------+"
 echo "|                        WSO2 Android Tryit                      |"
 echo "+----------------------------------------------------------------+"
+echo "Detected OS: " $OSTYPE
 if [ ! -f "sdklocation" ]; then
     echo -n "Do you have Android SDK installed in your computer (Y/n)?: "
     read answer
@@ -143,15 +150,15 @@ if [ ! -d "$ANDROID_TRYIT_SDK_HOME/build-tools/25.0.2" ]; then
     echo
     echo "Downloading Android build tools..."
     cd $ANDROID_TRYIT_SDK_HOME
-    curl -O https://dl.google.com/android/repository/build-tools_r25.0.2-linux.zip
-    [ -f "build-tools_r25.0.2-linux.zip" ] || { echo "Download failed. Aborting." ; exit 1 ;}
+    curl -O https://dl.google.com/android/repository/build-tools_r25.0.2-$OS_SUFFIX.zip
+    [ -f "build-tools_r25.0.2-$OS_SUFFIX.zip" ] || { echo "Download failed. Aborting." ; exit 1 ;}
     echo
     echo -n "Configuring Android build tools..."
-    unzip -q build-tools_r25.0.2-linux.zip
+    unzip -q build-tools_r25.0.2-$OS_SUFFIX.zip
     mkdir -p build-tools/25.0.2
     mv android-7.1.1/* build-tools/25.0.2/
     rm -r android-7.1.1
-    rm build-tools_r25.0.2-linux.zip
+    rm build-tools_r25.0.2-$OS_SUFFIX.zip
     echo "   Done!"
 fi
 
